target_panels: {
  lat_error: [
    "control_debug:lat_error",
  ],
  heading: [
    "vehicle_state:heading",
    "control_debug:nearest_point_heading",
  ],
  heading_error: [
    "control_debug:heading_error",
  ],
  front_angle: [
    "vehicle_state:front_angle",
    "control_cmd:target_front_angle",
  ],
  curvature: [
    "vehicle_state:curvature",
    "control_debug:nearest_point_curvature",
  ],
  v_error: [
    "control_debug:v_error",
  ],
  steering: [
    "vehicle_state:steering_wheel_angle",
    "control_cmd:target_steering_angle",
  ],
  speed: [
    "vehicle_state:v",
    "control_debug:nearest_point_v",
  ],
  acc: [
    "vehicle_state:acc",
    "control_cmd:target_acc",
    "control_debug:nearest_point_acc",
  ],
  torque: [
    "vehicle_state:torque",
    "control_cmd:target_torque",
  ],
  brake: [
    "vehicle_state:brake",
    "control_cmd:target_brake",
  ],
  gear: [
    "vehicle_state:gear_state",
    "control_cmd:target_gear",
  ],
  heading_rate: [
    "vehicle_state:heading_rate",
  ],
  pitch: [
    "vehicle_state:pitch",
  ],
  segment_id: [
    "trajectory:segment_id",
  ],
}