# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='controller.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x63ontroller.proto\"\xfc\x01\n\x0e\x43ontrolCommand\x12%\n\x0clon_cmd_type\x18\x01 \x01(\x0e\x32\x0f.LonCommandType\x12\x15\n\rtarget_torque\x18\x02 \x01(\x01\x12\x14\n\x0ctarget_brake\x18\x03 \x01(\x01\x12\x12\n\ntarget_acc\x18\x04 \x01(\x01\x12%\n\x0clat_cmd_type\x18\x05 \x01(\x0e\x32\x0f.LatCommandType\x12\x1a\n\x12target_front_angle\x18\x06 \x01(\x01\x12\x1d\n\x15target_steering_angle\x18\x07 \x01(\x01\x12 \n\x0btarget_gear\x18\x08 \x01(\x0e\x32\x0b.TargetGear\"\xd7\x01\n\x0c\x43ontrolDebug\x12\x18\n\x10nearest_point_id\x18\x01 \x01(\x05\x12\x17\n\x0fnearest_point_v\x18\x02 \x01(\x01\x12\x19\n\x11nearest_point_acc\x18\x03 \x01(\x01\x12\x1d\n\x15nearest_point_heading\x18\x04 \x01(\x01\x12\x1f\n\x17nearest_point_curvature\x18\x05 \x01(\x01\x12\x0f\n\x07v_error\x18\x06 \x01(\x01\x12\x11\n\tlat_error\x18\x07 \x01(\x01\x12\x15\n\rheading_error\x18\x08 \x01(\x01\"\x81\x01\n\x10\x43ontrollerOutput\x12$\n\x0b\x63ontrol_cmd\x18\x01 \x01(\x0b\x32\x0f.ControlCommand\x12$\n\rcontrol_debug\x18\x02 \x01(\x0b\x32\r.ControlDebug\x12\x15\n\rcontroller_id\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x03(\x05*0\n\x0eLonCommandType\x12\x07\n\x03\x41\x43\x43\x10\x01\x12\n\n\x06TORQUE\x10\x02\x12\t\n\x05\x42RAKE\x10\x03*;\n\x0eLatCommandType\x12\x0f\n\x0b\x46RONT_ANGLE\x10\x01\x12\x18\n\x14STEERING_WHEEL_ANGLE\x10\x02*,\n\nTargetGear\x12\x0e\n\nGEAR_CMD_R\x10\x01\x12\x0e\n\nGEAR_CMD_D\x10\x02')
)

_LONCOMMANDTYPE = _descriptor.EnumDescriptor(
  name='LonCommandType',
  full_name='LonCommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACC', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TORQUE', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BRAKE', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=625,
  serialized_end=673,
)
_sym_db.RegisterEnumDescriptor(_LONCOMMANDTYPE)

LonCommandType = enum_type_wrapper.EnumTypeWrapper(_LONCOMMANDTYPE)
_LATCOMMANDTYPE = _descriptor.EnumDescriptor(
  name='LatCommandType',
  full_name='LatCommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FRONT_ANGLE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STEERING_WHEEL_ANGLE', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=675,
  serialized_end=734,
)
_sym_db.RegisterEnumDescriptor(_LATCOMMANDTYPE)

LatCommandType = enum_type_wrapper.EnumTypeWrapper(_LATCOMMANDTYPE)
_TARGETGEAR = _descriptor.EnumDescriptor(
  name='TargetGear',
  full_name='TargetGear',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GEAR_CMD_R', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_CMD_D', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=736,
  serialized_end=780,
)
_sym_db.RegisterEnumDescriptor(_TARGETGEAR)

TargetGear = enum_type_wrapper.EnumTypeWrapper(_TARGETGEAR)
ACC = 1
TORQUE = 2
BRAKE = 3
FRONT_ANGLE = 1
STEERING_WHEEL_ANGLE = 2
GEAR_CMD_R = 1
GEAR_CMD_D = 2



_CONTROLCOMMAND = _descriptor.Descriptor(
  name='ControlCommand',
  full_name='ControlCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lon_cmd_type', full_name='ControlCommand.lon_cmd_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_torque', full_name='ControlCommand.target_torque', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_brake', full_name='ControlCommand.target_brake', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_acc', full_name='ControlCommand.target_acc', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat_cmd_type', full_name='ControlCommand.lat_cmd_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_front_angle', full_name='ControlCommand.target_front_angle', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_steering_angle', full_name='ControlCommand.target_steering_angle', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_gear', full_name='ControlCommand.target_gear', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=273,
)


_CONTROLDEBUG = _descriptor.Descriptor(
  name='ControlDebug',
  full_name='ControlDebug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nearest_point_id', full_name='ControlDebug.nearest_point_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nearest_point_v', full_name='ControlDebug.nearest_point_v', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nearest_point_acc', full_name='ControlDebug.nearest_point_acc', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nearest_point_heading', full_name='ControlDebug.nearest_point_heading', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nearest_point_curvature', full_name='ControlDebug.nearest_point_curvature', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_error', full_name='ControlDebug.v_error', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat_error', full_name='ControlDebug.lat_error', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading_error', full_name='ControlDebug.heading_error', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=491,
)


_CONTROLLEROUTPUT = _descriptor.Descriptor(
  name='ControllerOutput',
  full_name='ControllerOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='control_cmd', full_name='ControllerOutput.control_cmd', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='control_debug', full_name='ControllerOutput.control_debug', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controller_id', full_name='ControllerOutput.controller_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='ControllerOutput.id', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=623,
)

_CONTROLCOMMAND.fields_by_name['lon_cmd_type'].enum_type = _LONCOMMANDTYPE
_CONTROLCOMMAND.fields_by_name['lat_cmd_type'].enum_type = _LATCOMMANDTYPE
_CONTROLCOMMAND.fields_by_name['target_gear'].enum_type = _TARGETGEAR
_CONTROLLEROUTPUT.fields_by_name['control_cmd'].message_type = _CONTROLCOMMAND
_CONTROLLEROUTPUT.fields_by_name['control_debug'].message_type = _CONTROLDEBUG
DESCRIPTOR.message_types_by_name['ControlCommand'] = _CONTROLCOMMAND
DESCRIPTOR.message_types_by_name['ControlDebug'] = _CONTROLDEBUG
DESCRIPTOR.message_types_by_name['ControllerOutput'] = _CONTROLLEROUTPUT
DESCRIPTOR.enum_types_by_name['LonCommandType'] = _LONCOMMANDTYPE
DESCRIPTOR.enum_types_by_name['LatCommandType'] = _LATCOMMANDTYPE
DESCRIPTOR.enum_types_by_name['TargetGear'] = _TARGETGEAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlCommand = _reflection.GeneratedProtocolMessageType('ControlCommand', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLCOMMAND,
  __module__ = 'controller_pb2'
  # @@protoc_insertion_point(class_scope:ControlCommand)
  ))
_sym_db.RegisterMessage(ControlCommand)

ControlDebug = _reflection.GeneratedProtocolMessageType('ControlDebug', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLDEBUG,
  __module__ = 'controller_pb2'
  # @@protoc_insertion_point(class_scope:ControlDebug)
  ))
_sym_db.RegisterMessage(ControlDebug)

ControllerOutput = _reflection.GeneratedProtocolMessageType('ControllerOutput', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLEROUTPUT,
  __module__ = 'controller_pb2'
  # @@protoc_insertion_point(class_scope:ControllerOutput)
  ))
_sym_db.RegisterMessage(ControllerOutput)


# @@protoc_insertion_point(module_scope)
